[build]
  base = "/"
  publish = "build/"
  command = "yarn run csv-all && yarn test && yarn build"

[build.environment]
    PUBLIC_URL = "/"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
